# Generated by Django 3.0.7 on 2020-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='day',
            field=models.CharField(choices=[('', 'выбери день'), ('Monday', 'понедельник'), ('Tuesday', 'вторник'), ('Wednesday', 'среда'), ('Thursday', 'четверг'), ('Friday', 'пятница')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='week',
            field=models.CharField(choices=[('', 'выбери неделю'), ('1', '1'), ('2', '2')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
