# Generated by Django 3.0.7 on 2020-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('select', 'Выбери тип продукта'), ('business_lunch', 'Бизнес ланч'), ('soups', 'Супы'), ('hot_course', 'Горячее'), ('garnishes', 'Гарниры'), ('salads', 'Салаты'), ('drinks', 'Напитки')], default='', max_length=20),
        ),
    ]
